import {useEffect,useRef, type ReactNode} from 'react';
import type {Interval} from '../lib/types';
import {labels,duration,pct} from '../lib/store';
export function Drawer({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const before=document.activeElement as HTMLElement;ref.current?.querySelector<HTMLButtonElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=[...ref.current!.querySelectorAll<HTMLElement>('button,a,input,select,[tabindex="0"]')];const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);before?.focus();};},[onClose]);
 return <div className="drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className="drawer" ref={ref} role="dialog" aria-modal="true" aria-labelledby="drawer-title"><div className="panel-heading"><span className="eyebrow">BEHIND THE SIGNAL</span><button aria-label="Close evidence drawer" onClick={onClose}>✕</button></div><h2 id="drawer-title">{title}</h2>{children}</div></div>;
}
export function EvidenceDetail({interval:i}:{interval:Interval}){return <><div className="badge" style={{marginBottom:20}}>{labels[i.category]} · {duration(i.durationMs)}</div><p>{new Date(i.startedAt).toLocaleString()} — {new Date(i.endedAt).toLocaleTimeString()}</p><h3>Observed metadata</h3><p><strong>{i.app||'No app recorded'}</strong><br/>{i.title||'No window title recorded'}</p><p className="muted">{i.observationIds.length} observation(s){i.simulated?' · Simulated input':''}</p><h3>Analyzer evidence claims</h3><p className="muted">These reasons are reported by the analyzer; they are not independently verified facts.</p><ul>{i.evidence.map((e,n)=><li key={n}>{e}</li>)}</ul><h3>Interpretation</h3><p>{i.explanation}</p><div className="detail-grid"><span>Relevance<strong>{i.goalRelevance==null?'No data':pct(i.goalRelevance*100)}</strong></span><span>Confidence<strong>{pct(i.confidence*100)}</strong></span></div><p className="muted">Confidence is an uncalibrated estimate. Classifications can be wrong.</p><h3>Analysis & privacy</h3><p>{i.analysis?`${i.analysis.provider}${i.analysis.model?' · '+i.analysis.model:''} · ${i.analysis.modality}`:'No analysis for this interval'}</p><p>Screenshot: {i.screenshotRetention.replaceAll('-',' ')}</p>{i.analysis?.note&&<p className="notice">{i.analysis.note}</p>}</>;}
