export type Category = 'core'|'supporting'|'unknown'|'drift'|'distraction'|'recovery'|'unobserved'|'paused';
export interface Analysis { provider:string; model:string|null; modality:string; screenshotRetention:string; usedScreenshot:boolean; degraded:boolean; note:string|null }
export interface Observation { id:string; type:string; time:string; app:string; title:string; category:Category; reason:string; evidence:string[]; confidence:number; analysis:Analysis; taskContext:string|null; simulated:boolean }
export interface Interval { id:string; startedAt:string; endedAt:string; durationMs:number; app:string|null; title:string; category:Category; explanation:string; evidence:string[]; confidence:number; goalRelevance:number|null; analysis:Analysis|null; screenshotRetention:string; simulated:boolean; observationIds:string[]; observations?:Observation[] }
export interface Metrics { sessionScore:number|null; goalAlignment:number|null; focusContinuity:number|null; contextStability:number|null; band:string; confidence:number|null; coverage:number|null; uncertainty:string[]; durationsMs:Record<string,number>; shares:Record<string,number|null>; focus:{blockCount:number; longestBlockMs:number; medianBlockMs:number|null}; contextSwitches:number; switchDensityPerHour:number|null; method:Record<string,string>; timeline:Interval[] }
export interface Privacy { excludedApps:string[]; screenshotsEnabled:boolean; retention:'retain'|'discard-after-analysis'; retentionMinutes:number; analysisLocation:'metadata-only'|'local'|'cloud'; cloudConsent:boolean }
export interface Voice { enabled:boolean; voice:string|null; rate:number; cooldownMinutes:number; sustainedDriftSeconds:number; minConfidence:number }
export interface Intervention { id:string; triggeredAt:string; stage:string; transcript:string; reason:string; evidence:string[]; dismissed:boolean; lifecycle:{stage:string; at:string; silent?:boolean}[]; outcome?:{observation:string; caveat:string; before:{alignedShare:number|null; observedMs:number}; after:{alignedShare:number|null; observedMs:number}} }
export interface Analyzer { provider:string; state:string; detail:string; note?:string|null; modality:string }
export interface Session { id:string; goal:string; status:'live'|'paused'|'stopped'; startedAt:string; endedAt:string|null; simulated:boolean; mode:string; events:Observation[]; metrics:Metrics|null; privacy:Privacy; voice:Voice; interventions:Intervention[]; analyzer:Analyzer|null; capture:{enabled:boolean; status:string; lastError:string|null; screenshots:boolean}; coach:{state:string; muteUntil:string|null; suppressedReason:string|null}; pauses:{startedAt:string; endedAt:string|null}[] }
export interface Report { goal:string; durationLabel:string; selfReportedOutcome:string|null; metrics:Metrics; timeline:Interval[]; interventions:Intervention[]; friction:{pattern:string; detail:string; evidence:string[]}[]; nextExperiment:{experiment:string; measure:string}; limitations:string[]; observedFacts:{observationCount:number; analyzers:string[]; screenshotsUsed:boolean} }
export interface Settings { privacy:Privacy; voice:Voice; observer:{intervalMs:number}; analyzer:{provider:string} }
export interface Meta { permissions:{accessibility:string; screenRecording:string; detail:string|null}; analyzer:Analyzer; voice:{available:boolean; provider:string}; defaultExcludedApps:string[]; loadError:string|null }
